Traceback (most recent call last):
  File "/work/ch0636/g300128/Hydrologie_Calibration/Calibration/scripts/calibration_single_test_netcdf.py", line 415, in <module>
    with open(checkpoint, "wb") as cp_file:
FileNotFoundError: [Errno 2] No such file or directory: '/work/ch0636/g300128/Hydrologie_Calibration/Calibration/runs_calibration_12_params/2316/checkpoint.pkl'
